### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by stxupengyu** [shuiqukeyou/itag_py3#1]
你好，我也在复现这篇论文，我已经处理好了数据。我是一名NLP方面的新手，有三个参数我不太理解。
请问START_TOKEN,END_TOKEN,LABEL_FROM三个参数的具体含义是什么？
关于START_TOKEN,END_TOKEN，是否是tag对应的vocab里START和END的索引值？

**Comment by shuiqukeyou** [comment]
START_TOKEN,END_TOKEN是seq2seq模型输出端需要给定的两个参数，去看看seq2seq模型的输出流程就知道这两个值是啥意思了，不是本项目特有的。
LABEL_FROM是因为这个项目把文本词和tag词编到了同一个编号组里，需要有一个值标记tag是从哪个位置开始进行编号的，编号过程请查看dataload文件里的相关函数
