### ISSUE TITLE
请问您这边复现成功后可以比baseline好多少？

### ISSUE THREAD

**Issue by stxupengyu** [shuiqukeyou/itag_py3#2]
不知道您是否对比过ITAG和普通的神经网络，LSTM或者TLSTM的效果？F1大概能提升多少呢？

**Comment by shuiqukeyou** [comment]
和TLSTM的对比论文里有啊，TLSTM是基线之一，F1平均（@1、@3、@5）能锤大十几个点，[我做的结果](https://shuiqu.moe/2020/09/24/lstm%E2%80%94-experiment/)也是这样，论文并没有吹水。要是比单纯的LSTM就更吊打了

这玩意儿锤一个最简单的seq2seq理论上随便锤个二十个点的F1的提升（因为结果过于显然我实际上并没有做过）
但是有一个例外情况，如果数据量足够小，这个模型反而锤不过最简单的seq2seq，因为数据集不够这个模型学习的
这个情况我的一篇[博客](https://shuiqu.moe/2020/09/26/%E5%9C%A8seq2seq%E7%BB%93%E6%9E%84%E4%B8%AD%E6%8F%92%E5%85%A5GCN%E7%9A%84%E4%B8%80%E4%B8%AA%E5%AE%9E%E9%AA%8C/)里有提

这模型基本是用RNN的seq2seq做多tag推荐的巅峰了，叠加了一堆成熟的机制，而且还全部互相相关，完全改不动，我导师已经让我换东西了，磕这个模型磕得蛋疼，当然可能你能找到更好的方案

**Comment by stxupengyu** [comment]
感谢！非常solid的解答！
