### ISSUE TITLE
评估函数方面的问题

### ISSUE THREAD

**Issue by stxupengyu** [shuiqukeyou/itag_py3#3]
非常感谢您带注释版本的代码，为其他研究者们节省了大量时间！想和您交流下我近期发现的ITAG代码评估函数方面的问题。
代码中 MAX_LENGTH = 5 的时候，实际只预测了四个标签（最后一个是‘’END_TOKEN‘’），因而得到的评价指标实际是Precison@4。
这一点从Precision的计算可以看出来：
`    # 计算精确度
    if len(intersection) > 0:
        tmp_precision = len(intersection) * 1.0 / len(decoder_seq_set)`
其中len(decoder_seq_set)=4。因而实际上是Precison@4的计算公式。
您觉得我这样的理解对吗？

**Comment by shuiqukeyou** [comment]
这种理解是对的，到底是@5还是@4看你怎么定义，毕竟成功预测终止符也是预测成功。按itag代码的定义，precison@5是指预测五个的时的精确度，而不管这5个里面是不是有终止符。
它这算是取巧的做法，itag的三个数据集的平均tag数都只有3个，所以大部分数据集最后会被加上终止符，然后模型能成功预测出终止符当然也算成功预测。
因为终止符号在seq2seq模型里是必须的，所以这里就面临一个问题，到底要不要把终止符算成成功预测。在itag已经这么做了的情况下，你如果不把终止符当作一次成功预测，指标会低很多，尤其是@5的。但如果你写成@4，这不符合惯例（惯例是@1@3@5）。
如果你写成了不计算终止符的@5。意味着你需要实际预测6个，然后删除终止符。这样做的问题在于，和上面一样指标会低很多，另外有些情况下seq2seq模型不会输出终止符，这种情况下你实打实的预测出了6个，你就需要决定删掉哪一个，比如你一刀切删掉第六个的话，第六个有可能是正确的tag，就还得考虑这个问题。
我当初是没管是否有终止符，@5就是进行五次预测。

2021年6月25日(金) 20:07 Pangyu ***@***.***>:

**Comment by stxupengyu** [comment]
如果将终止符也算作预测正确，这样对于baseline而言不公平。  
这篇文章的评价指标感觉还是有不小的问题。

**Comment by shuiqukeyou** [comment]
这篇文章有问题的地方不止这个评价指标，它论文里提到的三大创新机制，其中之一是一个指示函数（原文叫啥忘了，太久了，现在手边也没有论文），然而代码里并没有。
在注意力层里有个写了个半截的指示函数，有输出值，但是并不进行训练，也不参与后续运算（因为后续运算就是接softmax进行预测了），你删掉它对性能也没有任何影响。即，它的源码只有两个机制，但是就算只有两个机制，性能也还可以，能复现（@5还是@4这个问题另说），但是从创新型来说就比它论文里写的弱的多了，注意力+共享嵌入层又不是什么新鲜东西。
虽然说源码对不上论文不是什么少见的事，但是既然给了源码却还留了这么个漏洞就很奇怪。

Pangyu ***@***.***> 于2021年7月15日周四 下午3:57写道：

**Comment by stxupengyu** [comment]
感谢老哥的解答
